<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="display-2 text-center">Lista de tareas</h2>
			<a href="<?php echo APP_URL. "tareas/agregar"; ?>" class="btn btn-outline-primary mb-3">Agregar tarea</a>
            <a href="<?php echo APP_URL. "categorias/index"; ?>" class="btn btn-outline-primary mb-3">Ver categorias</a>
			<table border="1" class="table table-striped table-responsive-lg">
				<tr class="thead-dark">
					<th>ID</th>
					<th>Nombre</th>
					<th>Fecha</th>
					<th>Prioridad</th>
					<th>Categorias</th>
					<th>Acción</th>
				</tr>
                    <?php foreach ($this->tareas as $tarea): ?>
				<tr>
					<td><?php echo $tarea["tareas"]["id"]; ?></td>
					<td><?php echo $tarea["tareas"]["nombre"]; ?></td>
					<td><?php echo $tarea["tareas"]["fecha"]; ?></td>
					<td><center><?php
                        if ($tarea["tareas"]["prioridad"]<=3) {
                            echo '<button type="button" class="btn btn-success" >Baja</button>';
                        }elseif ($tarea["tareas"]["prioridad"]<=6) {
                            echo '<button type="button" class="btn btn-warning" >Media</button>';
                        }elseif ($tarea["tareas"]["prioridad"]<=10) {
                            echo '<button type="button" class="btn btn-danger" >Alta</button>';
                        }   
                    ?></center></td>
					<td><?php echo $tarea["categorias"]["nombre"]; ?></td>
					<td> <center><a href="<?php echo APP_URL. "tareas/editar/". $tarea["tareas"]["id"]; ?>" class="btn btn-primary mr-3">Editar</a><a href="<?php echo APP_URL. "tareas/eliminar/". $tarea["tareas"]["id"]; ?>" class="btn btn-danger mr-3">Eliminar</a>
					<?php

					if ($tarea["tareas"]["status"]==1) { ?>
						<a href="<?php echo APP_URL. "tareas/cambiarEstado/".$tarea["tareas"]["id"]."/off"; ?>" class="btn btn-success">Deshabilitar</a>

					<?php }elseif ($tarea["tareas"]["status"]==0) { ?>
						<a href="<?php echo APP_URL. "tareas/cambiarEstado/".$tarea["tareas"]["id"]."/on"; ?>" class="btn btn-success">Habilitar</a>
					<?php } ?>
					</center></td>
				</tr>
				<?php endforeach; ?>
			</table>
		</div>
	</div>
</div>